### ISSUE TITLE
Notify of failed deploys in a different channel

### ISSUE THREAD

**Issue by stevenhaddox** [supremegolf/slackistrano#17]
In our team setup we have a #deploys channel as well as a #errors channel. Most folks mute the #deploys channel, but it would be an awesome option to be able to post failed deploy notifications to the #errors channel where it might get a quick response from someone able to go look into the CI's build and determine why capistrano failed.

Obviously this isn't a huge deal, just a nice to have feature I thought I'd suggest.

Thanks for all your great work on slackistrano. It's worked very very well so far.

**Comment by phallstrom** [comment]
@stevenhaddox I like that.  Doubt I'd use it myself, but I can see why you'd want it.  Just pushed 0.1.17 to rubygems.  Update your deploy config:

```
set :slack_channel,          -> { '#general' }
set :slack_channel_starting, -> { nil } # Channel to post to. Optional. Defaults to :slack_channel.
set :slack_channel_finished, -> { nil } # Channel to post to. Optional. Defaults to :slack_channel.
set :slack_channel_failed,   -> { nil } # Channel to post to. Optional. Defaults to :slack_channel.
```

**Comment by stevenhaddox** [comment]
That was fast! Thanks!
