### ISSUE TITLE
set :slack_channel is mandatory for slackbot

### ISSUE THREAD

**Issue by osaris** [supremegolf/slackistrano#24]
Hello,

Thanks for this gem, it works perfectly but readme doesn't seems up2date and we need to set slack_channel to get it working using slackbot.

No error is reported if channel isn't set, I had to dig to https://github.com/supremegolf/slackistrano/blob/242890bc7bdb12064250180210087d7dd9c5861a/lib/slackistrano/tasks/slack.rake#L88 to find the cause.

Regards,

Raphaël

**Comment by phallstrom** [comment]
What would you change in the README?  Can you submit a PR with copy updates? Thx!

**Comment by osaris** [comment]
I'll make a PR but in 2 words, README must say that set :slack_channel is mandatory to get notifications. I first thought that slack_channel is set by default to '#general' (which is ok) and that I can optionally override. It's not optional, it's mandatory ;-)

**Comment by osaris** [comment]
Proposal in #25

**Comment by phallstrom** [comment]
Handled in #25.
